{% set name = "kivymd" %}
{% set version = "0.104.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97bc1f9442d25ff9dbd617d5ca74d53e757b92c68636a388e22d3f05a4f19c12

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kivy >=2.0.0
    - pillow

test:
  imports:
    - kivymd

about:
  home: https://kivymd.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of Material Design compliant widgets for use with Kivy
  doc_url: https://kivymd.readthedocs.io/en/latest/
  dev_url: https://github.com/kivymd/KivyMD

extra:
  recipe-maintainers:
    - scopatz
