{% set name = "kivymd" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4274721bd9672d507fbe70dc5173a1ce8c57d9f305f91d2bea58bf588c49fe62

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kivy >=2.0.0
    - pillow

test:
  imports:
    - kivymd

about:
  home: https://kivymd.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of Material Design compliant widgets for use with Kivy
  doc_url: https://kivymd.readthedocs.io/en/latest/
  dev_url: https://github.com/kivymd/KivyMD

extra:
  recipe-maintainers:
    - scopatz
